# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "unicorn-testing"
include-before = [
	"configurations.cmake"
]

[subdir.unicorn]

[target.test-unicorn]
type = "executable"
sources = ["src/**.cpp", "src/**.h"]
compile-features = ["cxx_std_20"]
link-libraries = ["unicorn-static"]
compile-definitions = ["NOMINMAX"]
